### PR TITLE
Added cuttlebelle

### PR DESCRIPTION
**Pull request by dominikwilkowski**
Hi there,

I added [Cuttlebelle](https://cuttlebelle.com/) to the examples. This is a great tool to compare the strength and weaknesses of these static site generators. Cheers

P.S.: I left the root README.md file unchanged to avoid merge conflicts (and I wasn't sure how it's ordered)

### CODE REVIEW

**Comment by geraldb** [comment]
@dominikwilkowski  Wow. Fantastic. Thanks for adding Cuttlebelle.

PS: Let me know if you're interested in joining the github org - so you can just in case change / update the sample in place (without pull request) etc. If interested let me know and I send you an invitation (via github by email). Keep it up. Thanks again. Cheers. Prost. Happy Easter.

**Comment by dominikwilkowski** [comment]
No worries from down under :)
and yeah sure add me to the org. Happy to carry the flag.

**Comment by dominikwilkowski** [comment]
The link https://staystatic.github.io/sites/cuttlebelle/ doesn't resolve yet and the root readme is missing cuttlebelle still. Happy to fix the readme, not sure how the other repo adds the site folders. Do you have automation setup there?

**Comment by geraldb** [comment]
@dominikwilkowski  Great. Welcome.  Note: You will get an invitation (by email from GitHub) to join the stay static org as a member. If you accept, you can update the page in your browser  - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/staystatic/people)). Greetings from Vienna, Austria. All the best with Cuttlebelle. Keep it up. Cheers. Prost.

**Comment by geraldb** [comment]
> The link https://staystatic.github.io/sites/cuttlebelle/ doesn't resolve yet and the root readme is missing cuttlebelle still. Happy to fix the readme, not sure how the other repo adds the site folders. Do you have automation setup there?

Sorry no automation for the setup - what I do is - build the site local "by hand" and than check in / commit / push the output folder (it's all static ;-) into the /sites/cuttlebell folder in <https://github.com/staystatic/staystatic.github.io/tree/master/sites>. Let me know if it works or if I can help out or assist or if you have questions etc.  Thanks again for adding Cuttlebelle. Cheers.

**Pull request merged**
