### PR TITLE
Add Phenomic React App example

### PR DESCRIPTION
**Pull request by MoOx**
Hope it's ok the way I made it!

### CODE REVIEW

**Comment by MoOx** [comment]
(Will have to push a tiny fix before pushing on the website)

**Comment by geraldb** [comment]
@MoOx  Wow. Again. Thanks for the Phenomic sample. Please, commit and add the source sample.

FYI: The generated website sample (that is, the static HTML, etc.) goes into `sites/phenomic` in the `staystatic.github.io` repo - see <https://github.com/staystatic/staystatic.github.io/tree/master/sites>. If I can assist or help, let me know, Keep it up. Great stuff. Thanks again. Will later also send out "promotion" tweets and if it gets accepted a talk about Phenomic (and React) at the local Vienna React meetup. Cheers. Prost.

**Comment by MoOx** [comment]
Will push an update to the website with the compiled result

**Comment by geraldb** [comment]
@MoOx  Thanks for adding the compiled site (for the "live" preview). Happy easter. Cheers. Prost.

**Pull request merged**
