### PR TITLE
Nikola Sample Site

### PR DESCRIPTION
**Pull request by ralsina**
To build, install Nikola and run "nikola build", output will be in `output/`

It could be made waaaaay simpler but I just took the default Nikola site from `nikola init` and did minimal modifications needed.

If there's anything wrong/missing in this sample site, or anything else I should do, let me know.

### CODE REVIEW

**Comment by geraldb** [comment]
@ralsina  Wow. Fantastic. Thanks for adding Nikola. Will send out announcements later this week add your credits etc. Thanks again.

**Comment by geraldb** [comment]
@ralsina  Maybe you can help / advise. Since the site gets hosted at  /site/nikola/...  - Do you know if there's a way I can add a prefix / site.path to absolute links? e.g. currently its

```
  <link rel="stylesheet" href="/css/style.css">
```

but the sample needs something like

```
 <link rel="stylesheet" href="[[prefix]]/css/style.css">  leading to
 <link rel="stylesheet" href="/site/nikola/css/style.css">
```

Not sure if that make sense e.g. for example can I use define a SITE_PATH=/site/nikola constant in config.py and use something like:

```
<link rel="stylesheet" href="%{SITE_PATH}/css/style.css">
```

Thanks again.  Still learning Nikola.

**Comment by ralsina** [comment]
Just change the SITE_URL in conf.py to wherever the site will really be and it should Just Work (TM) and don't worry about the paths in the site itself.

**Comment by geraldb** [comment]
@ralsina  Great. Fantastic. FYI: The Nikola sample site is now live http://staystatic.github.io/sites/nikola. Thanks again.

**Pull request merged**
